import type { Metadata } from "next";
import { poppins } from "@/app/ui/fonts";
import "@/app/ui/globals.css";
import { ReduxProvider } from "../app/redux/provider";
import { AppProvider } from "../AppContext";
import { ToastContainer, Slide } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "Be Well",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <ReduxProvider>
          <AppProvider>{children}</AppProvider>
        </ReduxProvider>
        <ToastContainer
          position="top-center"
          autoClose={3000}
          transition={Slide}
        />
      </body>
    </html>
  );
}
